# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.5"
manifest_format = "2.0"
project_hash = "20620afeaa58c7e60ac5c1af885bea9723a0757b"

[[deps.FornbergFiniteDiff]]
git-tree-sha1 = "4b13b442b119ac4242c1724e917c9a4801ccc49d"
repo-rev = "main"
repo-url = "https://github.com/runtosolve/FornbergFiniteDiff.jl.git"
uuid = "bc6155a8-87c8-416d-b52d-44cfacf6a7f1"
version = "0.1.0"
