name = "InternalForces"
uuid = "0ac833a1-d586-4577-9e6b-83a7c69b6692"
authors = ["Cris Moen <cris.moen@runtosolve.com>"]
version = "0.1.0"

[deps]
DiffEqOperators = "9fdde737-9c7f-55bf-ade8-46b3f136cc48"
